# -*- coding: utf-8 -*-
"""PalmerPenguinsM3PA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xyyy1xTBSSsSQP60bDBPtuVfoPure6W9
"""

# PalmerPenguinsM3.py
# James Parker
# 10/05/2026
# Uses lists and formatted output to analyze Palmer Penguin statistics.

# Import required modules
import math

# Constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

# Lists containing related penguin data
species_names = [
    SP_CHINSTRAP,
    SP_GENTOO,
    SP_ADELIE
]
species_counts = [
    NUM_CHINSTRAP,
    NUM_GENTOO,
    NUM_ADELIE
]

#Determine largest and smallest species group
largest_count = max(species_counts)
smallest_count = min(species_counts)
largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)
largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]

# Calculate dataset statistics
total_species = len(species_names)
total_penguins = sum(species_counts)

average_penguins = total_penguins / total_species
average_penguins_rounded_up = math.ceil(average_penguins)

chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100

# output the species names with introductory text and formatted statistics
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()
print(f"There are a total of {total_species} penguin species in this dataset.")
print(f"There are a total of {total_penguins} penguins in the dataset.")
print(f"The average number of penguins per species is "
  f"{average_penguins:.1f}.")
print(f"The average rounded up is {average_penguins_rounded_up}.")
print()
print(f"{species_names[0]}: {species_counts[0]} "
  f"({chinstrap_percent:.2f}%)")
print(f"{species_names[1]}: {species_counts[1]} "
  f"({gentoo_percent:.2f}%)")
print(f"{species_names[2]}: {species_counts[2]} "
  f"({adelie_percent:.2f}%)")
print()
print(f"The species with the most observations is {largest_species} with "
  f"{largest_count} penguins.")
print(f"The species with the fewest observations is {smallest_species} with "
  f"{smallest_count} penguins.")